//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzatorium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        public int dIngredientID { get; set; }
        public string dIngredient { get; set; }
        public Nullable<decimal> dCost { get; set; }
    }
}
