//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzatorium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class tblPizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPizza()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int dPizzaID { get; set; }
        public int dSizeID { get; set; }
        public string dIngredients { get; set; }
        public string dPizzaName { get; set; }
    
        public virtual tblSize tblSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers { get; set; }

        [NotMapped]
        public IEnumerable<tblIngredient> IngredientsCollection { get; set; }

        [NotMapped]
        public string[] SelectedIngredientIDArray { get; set; }

        [NotMapped]
        public IEnumerable<tblSize> SizesCollection { get; set; }

        [NotMapped]
        public string[] SelectedSizesIDArray { get; set; }
    }
}
